import { useCallback, useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, RefreshCw, Search, ShieldCheck } from "lucide-react";

import { api } from "../api/client";
import { ViralAnalysisResult } from "../components/viral/ViralAnalysisResult";
import type { DeveloperViralAnalysisJob, ViralAnalysisStatus } from "../types";

const pageSize = 20;
type Filters = { tenantId: string; status: "" | ViralAnalysisStatus };
const emptyFilters: Filters = { tenantId: "", status: "" };
function toParams(page: number, filters: Filters) { const params = new URLSearchParams({ page: String(page), page_size: String(pageSize) }); if (filters.tenantId) params.set("tenant_id", filters.tenantId); if (filters.status) params.set("status", filters.status); return params; }
function formatTime(timestamp: number) { return timestamp ? new Intl.DateTimeFormat("zh-CN", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(timestamp * 1000)) : "未记录"; }

export function DeveloperAIJobsPage() {
  const [filters, setFilters] = useState(emptyFilters);
  const [jobs, setJobs] = useState<DeveloperViralAnalysisJob[]>([]); const [detail, setDetail] = useState<DeveloperViralAnalysisJob | null>(null);
  const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const listRequest = useRef(0); const detailRequest = useRef(0); const selectedId = useRef<number | null>(null); const appliedFilters = useRef(emptyFilters);
  const selectJob = useCallback(async (jobId: number) => { const requestId = ++detailRequest.current; selectedId.current = jobId; try { const result = await api.getDeveloperViralAnalysisJob(jobId); if (requestId === detailRequest.current && selectedId.current === jobId) { setDetail(result); setMessage(""); } } catch (error) { if (requestId === detailRequest.current && selectedId.current === jobId) setMessage(error instanceof Error ? error.message : "任务详情加载失败。"); } }, []);
  const loadJobs = useCallback(async (requestedPage = 1, nextFilters = appliedFilters.current) => { const requestId = ++listRequest.current; setLoading(true); try { const result = await api.listDeveloperViralAnalysisJobs(toParams(requestedPage, nextFilters)); if (requestId !== listRequest.current) return; if (!result.items.length && result.total > 0 && requestedPage > 1) { void loadJobs(requestedPage - 1, nextFilters); return; } setJobs(result.items); setPage(result.page); setTotal(result.total); if (selectedId.current && !result.items.some((item) => item.id === selectedId.current)) { ++detailRequest.current; selectedId.current = null; setDetail(null); } } catch (error) { if (requestId === listRequest.current) setMessage(error instanceof Error ? error.message : "AI 任务列表加载失败。"); } finally { if (requestId === listRequest.current) setLoading(false); } }, []);
  useEffect(() => { void loadJobs(); }, [loadJobs]);
  const pageCount = Math.max(1, Math.ceil(total / pageSize)); const usage = detail?.latest_ai_usage;
  return <section className="page-stack developer-ai-jobs-page"><div className="page-heading horizontal-heading"><div><h1>AI 任务排查</h1><p>内部技术排查入口，用于核对爆款解析调用状态、耗时和算力记录。</p></div><button className="secondary-button compact" type="button" onClick={() => void loadJobs(page)}><RefreshCw size={16} />刷新任务</button></div>{message ? <div className="form-message" role="status">{message}</div> : null}
    <section className="panel developer-ai-filters" aria-label="AI 任务筛选"><label>租户 ID<input aria-label="租户 ID" value={filters.tenantId} inputMode="numeric" onChange={(event) => setFilters({ ...filters, tenantId: event.target.value })} /></label><label>任务状态<select aria-label="AI 任务状态" value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value as Filters["status"] })}><option value="">全部状态</option><option value="pending">待解析</option><option value="processing">解析中</option><option value="completed">已完成</option><option value="failed">失败</option><option value="cancelled">已取消</option></select></label><button className="primary-button compact" type="button" onClick={() => { appliedFilters.current = filters; void loadJobs(1, filters); }}><Search size={16} />应用筛选</button></section>
    <div className="developer-ai-workspace"><section className="panel developer-ai-list"><div className="panel-title"><h2>任务队列</h2><span>{total} 项</span></div>{loading ? <div className="inspiration-session-skeleton"><span /><span /><span /></div> : jobs.length ? <div className="viral-job-rows">{jobs.map((job) => <button key={job.id} type="button" className={detail?.id === job.id ? "viral-job-row active" : "viral-job-row"} onClick={() => void selectJob(job.id)}><span><strong>#{job.id} {job.title}</strong><small>租户 {job.tenant_id} · 用户 {job.user_id}</small></span><span className={`viral-status ${job.status}`}>{job.status}</span></button>)}</div> : <div className="empty-list-state">没有可排查的 AI 任务。</div>}<div className="inspiration-pagination"><button className="table-action compact" type="button" disabled={loading || page <= 1} onClick={() => void loadJobs(page - 1)}><ChevronLeft size={15} />上一页</button><span>第 {page} 页 / 共 {total} 项</span><button className="table-action compact" type="button" disabled={loading || page >= pageCount} onClick={() => void loadJobs(page + 1)}>下一页<ChevronRight size={15} /></button></div></section>
      <section className="panel developer-ai-detail"><div className="panel-title"><h2><ShieldCheck size={18} />诊断详情</h2></div>{detail ? <><div className="viral-detail-meta"><strong>{detail.title}</strong><span>租户 {detail.tenant_id}</span><span>用户 {detail.user_id}</span><span>{formatTime(detail.update_time)}</span></div><dl className="developer-usage-grid"><div><dt>调用状态</dt><dd>{usage?.status ?? "暂无调用记录"}</dd></div><div><dt>服务商</dt><dd>{usage?.provider ?? "-"}</dd></div><div><dt>模型</dt><dd>{usage?.model_name ?? "-"}</dd></div><div><dt>耗时</dt><dd>{usage ? `${usage.latency_ms} ms` : "-"}</dd></div><div><dt>输入字符</dt><dd>{usage?.input_chars ?? "-"}</dd></div><div><dt>输出字符</dt><dd>{usage?.output_chars ?? "-"}</dd></div><div><dt>算力</dt><dd>{usage?.credit_cost ?? detail.credit_cost}</dd></div><div><dt>调用时间</dt><dd>{usage ? formatTime(usage.create_time) : "-"}</dd></div>{usage?.error_message ? <div className="wide"><dt>安全错误摘要</dt><dd>{usage.error_message}</dd></div> : null}</dl><ViralAnalysisResult result={detail.result} /></> : <div className="empty-list-state">选择一项 AI 任务查看内部诊断。</div>}</section></div>
  </section>;
}
